In [2]:
import torch
import math
# cutoff function from ANI
def cutoff_cosine(distances: torch.Tensor, cutoff: float) -> torch.Tensor:
    # assuming all elements in distances are smaller than cutoff
    return 0.5 * torch.cos(distances * (math.pi / cutoff)) + 0.5


In [5]:
from modelforge.potential.utils import CosineCutoff
from openff.units import unit

In [4]:
d_ij = torch.rand(
    5,
)
d_ij

tensor([0.2318, 0.6412, 0.9616, 0.1169, 0.0144])

In [19]:
cutoff = CosineCutoff(10*unit.angstrom)
cut = cutoff(d_ij)
cut

tensor([0.8732, 0.2855, 0.0036, 0.9667, 0.9995])

In [10]:
cutoff_cosine(d_ij, 1)

tensor([0.8732, 0.2855, 0.0036, 0.9667, 0.9995])

In [23]:
r = torch.rand((5, 8))
r

In [28]:
r.T * cut

tensor([[6.3368e-01, 7.2967e-02, 1.8300e-03, 1.7558e-02, 6.0962e-01],
        [2.3146e-02, 5.7950e-02, 1.7376e-03, 6.5122e-03, 6.6679e-01],
        [6.7432e-01, 2.4014e-01, 3.4891e-03, 2.5857e-01, 9.1486e-01],
        [7.6756e-01, 5.7948e-02, 1.0094e-03, 2.4969e-01, 4.1033e-01],
        [1.1968e-01, 5.6675e-02, 2.4570e-03, 7.1937e-01, 3.9575e-01],
        [1.6927e-02, 1.2842e-01, 2.2869e-04, 1.0420e-01, 5.3505e-01],
        [3.4283e-01, 8.7109e-02, 3.1950e-03, 7.1549e-01, 1.9351e-02],
        [4.1282e-01, 1.6380e-01, 1.6828e-03, 7.5173e-01, 4.9266e-01]])